DROP TABLE IF EXISTS trips CASCADE;
DROP TABLE IF EXISTS locations CASCADE;
DROP TABLE IF EXISTS canonical_trips CASCADE;
DROP TABLE IF EXISTS canonical_trips_relations CASCADE;
DROP TABLE IF EXISTS stays CASCADE;
